### PR TITLE
Example project (exmaple-simple based on documentation usage)

### PR DESCRIPTION
**Pull request by M0dM**
Hi,

I am writing some example project based on your usage documentation.
- example-simple will be exactly the use case from the documentation.
- example-with-children will be almost the same but with comment document as children of blogpost document in elasticsearch

This is still a work in progress.
Be free to ask me some code modifications if needed to feet the purpose of documentation.

I will try to follow code recommendation using flake8 & I will try to add some test using pytest.

EDIT : Only the first project inside this PR, the other will come within another pull request.

### CODE REVIEW

**Comment by CommandrAvander** [comment]
Sounds good, thanks for the heads up. You can also the original files here,
for reference.
https://github.com/CommandrAvander/elasticsearch-django-tutorial

On Tue, Mar 29, 2016 at 5:29 AM, Benoit Brayer <notifications@github.com>
wrote:

> Hi,
>
> I am writing some example project based on your usage documentation.
>
>    - example-simple will be exactly the use case from the documentation.
>    - example-with-children will be almost the same but with comment
>    document as children of blogpost document in elasticsearch
>
> This is still a work in progress.
> Be free to ask me some code modifications if needed to feet the purpose of
> documentation.
>
> I will try to follow code recommendation using flake8 & I will try to add
> some test using pytest.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/jaddison/django-simple-elasticsearch/pull/12
> Commit Summary
>
>    - Start of example projects (README & requirements)
>    - Flake8 and autopep8 added to help for code linting.
>    - Reorganized requirements in 3 categories : base / tools / test.
>    - Configure debug_toolbar
>    - clean code with flake8
>
> File Changes
>
>    - *A* examples/example-simple/.gitignore
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-0>
>    (119)
>    - *A* examples/example-simple/README.MD
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-1>
>    (47)
>    - *A* examples/example-simple/blog/__init__.py
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-2>
>    (0)
>    - *A* examples/example-simple/blog/admin.py
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-3>
>    (5)
>    - *A* examples/example-simple/blog/apps.py
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-4>
>    (6)
>    - *A* examples/example-simple/blog/forms.py
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-5>
>    (14)
>    - *A* examples/example-simple/blog/migrations/__init__.py
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-6>
>    (0)
>    - *A* examples/example-simple/blog/models.py
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-7>
>    (14)
>    - *A* examples/example-simple/blog/static/css/style.css
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-8>
>    (48)
>    - *A* examples/example-simple/blog/templates/blog/_base.html
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-9>
>    (22)
>    - *A* examples/example-simple/blog/templates/blog/_meta.html
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-10>
>    (3)
>    - *A* examples/example-simple/blog/templates/blog/_style.html
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-11>
>    (3)
>    - *A* examples/example-simple/blog/templates/blog/index.html
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-12>
>    (9)
>    - *A* examples/example-simple/blog/urls.py
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-13>
>    (6)
>    - *A* examples/example-simple/blog/views.py
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-14>
>    (5)
>    - *A* examples/example-simple/manage.py
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-15>
>    (10)
>    - *A* examples/example-simple/requirements/reqs_base.in
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-16>
>    (4)
>    - *A* examples/example-simple/requirements/reqs_base.txt
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-17>
>    (13)
>    - *A* examples/example-simple/requirements/reqs_test.in
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-18>
>    (2)
>    - *A* examples/example-simple/requirements/reqs_test.txt
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-19>
>    (12)
>    - *A* examples/example-simple/requirements/reqs_tools.in
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-20>
>    (4)
>    - *A* examples/example-simple/requirements/reqs_tools.txt
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-21>
>    (18)
>    - *A* examples/example-simple/requirements/requirements.txt
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-22>
>    (3)
>    - *A* examples/example-simple/website/__init__.py
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-23>
>    (0)
>    - *A* examples/example-simple/website/settings.py
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-24>
>    (132)
>    - *A* examples/example-simple/website/urls.py
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-25>
>    (28)
>    - *A* examples/example-simple/website/wsgi.py
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-26>
>    (16)
>    - *A* examples/example-with-children/README.MD
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-27>
>    (48)
>    - *A* examples/example-with-children/requirements/reqs_base.in
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-28>
>    (4)
>    - *A* examples/example-with-children/requirements/reqs_base.txt
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-29>
>    (13)
>    - *A* examples/example-with-children/requirements/reqs_dev.in
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-30>
>    (1)
>    - *A* examples/example-with-children/requirements/reqs_dev.txt
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-31>
>    (9)
>    - *A* examples/example-with-children/requirements/requirements.txt
>    <https://github.com/jaddison/django-simple-elasticsearch/pull/12/files#diff-32>
>    (2)
>
> Patch Links:
>
>    - https://github.com/jaddison/django-simple-elasticsearch/pull/12.patch
>    - https://github.com/jaddison/django-simple-elasticsearch/pull/12.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jaddison/django-simple-elasticsearch/pull/12>
>



-- 
*Adam Vanderbush*
adamvbush@gmail.com
@CommandrAvander <https://twitter.com/CommandrAvander>

**Comment by M0dM** [comment]
Coverage : 95%
flake8 : ok

I need to add few more docs inside the README.MD file but I think it's almost done for the 'example-simple' project.

Maybe it's better if you merge this before I write the 'example-with-children' one ?

**Comment by jaddison** [comment]
Hi @M0dM - I noticed that you were building against `master`; I'm currently in the midst of updating the code to a new version (see `es2.0` branch), which includes some breaking changes.

I'm sure your PR will merge smoothly when ready, but will be out of date with the planned changes in `es2.0`. Just an FYI.

Feel free to go either way with your proposed PR(s) - one big one or two separate ones. Your call.

**Comment by M0dM** [comment]
The thing is I never user this project with elasticsearch 2.x because I am actually using elasticsearch 1.7.5 provided by bonsai.io. So I don't really know what are the breaking change between elasticsearch yet.

Anyway, I will try to finish the other example with the same es version and see how to port these two example project on es 2.x after that.

I will edit the first message & title to match the 'example-simple' only PR and you can merge if it's ok for you. ;)

**Comment by jaddison** [comment]
Sorry, I didn't mean Elasticsearch 2.x - I meant that the new version of `django-simple-elasticsearch` will be 2.0 (the `es2.0` branch for this project has the changes). There are some changes that are NOT backwards compatible. I will see what I can do to minimize them, but I'm removing some functionality.

See https://github.com/jaddison/django-simple-elasticsearch/pull/13 for the current changes (likely more coming).

**Comment by M0dM** [comment]
Could we merge this inside a new 0.9.16 tag before we figured out what will break with new version 2.0 ?

**Comment by M0dM** [comment]
Hi jaddison,

Do you plan to merge this ?

**Pull request closed without merging**
